input {
  file {
    path => "/home/ubuntu/cowrie.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

filter {
  date {
    match => [ "timestamp", "ISO8601" ]
  }
  if [src_ip] {
    geoip {
      source => "src_ip"
      target => "geoip"
    }
  }
}

output {
  opensearch {
    hosts => ["https://search-honeypot-aacfpzl27fajlmhaz43xh6nr34.us-east-1.es.amazonaws.com:443"]
    auth_type => {
      type => "basic"
      user => "testmaster"
      password => "MD^7!OmyJFH9D#"
    }
    index => "cowrie-geo-%{+YYYY.MM.dd}"
    ssl => true
  }
}
